### ISSUE TITLE
GE: You can't create a folder in a Minio bucket without also creating an object

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/minio#107]
When you create a folder (via web client, mc, backup client like Veeam), the folder is automatically deleted unless you immediately create an object/file in the folder.

This can be easily reproduced:
- Create an S3 reservation
- In the minio web client, create a bucket
- Create a folder within the bucket
- Browse away / come back
- the folder will be gone.

You can make the folder stay around by:
- Create an S3 reservation
- In the minio web client, create a bucket
- Create a folder within the bucket
- Immediately upload a file to the folder
- then the folder will remain

Related example: https://github.com/threefoldtech/home/issues/843
The immediate folder deletion behaviour does not occur on a typical Minio installation. As an example, when Kapsch use their own Minio (installed on their own servers, not ThreeFold) they are able to get through the entire Veeam backup wizard, which creates a folder called "Veeam" in the selected bucket. When they try the same steps against a ThreeFold MInio reservation, the process fails when trying to create a folder called "Veeam".

Maybe related:
https://github.com/minio/minio/issues/5102

**Comment by muhamadazmy** [comment]
@joefoxton
I think I have found the issue, but I can't test with Veeam yet because I am trying to download the tool in the video (Veeam Backup Client) but I can't find such tool here https://www.veeam.com/downloads.html
Could you please tell me exactly which tool to download from that list.

**Comment by joefoxton** [comment]
@muhamadazmy Now that you have clarified how folder creation should work, I think we can close this issue and use https://github.com/threefoldtech/minio/issues/106 to deal with the issues at Kapsch.
