### ISSUE TITLE
investigate performance degradation issue 

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/minio#111]
The issue was reported first by the potential client environment:
- They use 125 shards with 100/25 data/parity setup 
- The upload goes fast at first, with noticeable dents in performance
- After a while the dents becomes wider (after at least 100GB) until the connection is dropped eventually
 
Trying to reproduce:
- we notice the dents (stops in the upload stream) also on a 16/4 env.
- we created some test locally that produce trace data, and we notice stops in the upload as well. 

Looking into this issue further trying to separate the cause of the issue, we pretty sure it's related to zdb running in sequential mode. 

Next:
- We looking into zdb to see if we can figure out why this stops are happening

**Comment by muhamadazmy** [comment]
So we finally know the reason for the performance degradation. It seems the way we store the metadata files on the filesystem is not very efficient when you have many small files, this cause the directory inodes to grow so big and make it slower and slower to store new metadata objects.

What we are doing right now is refactor the way we store the meta, to move to database instead of plane files on the harddisk. this should be much better for the performance, but will also take some time to completely finish the refactoring.

This change is unfortunately not backward compatible, so minio will not work directly against old installation. We can have 2 procedures for this:
- If the archive is empty or not important (test setup) we can wipe it clean and start over
- Introduce an upgrade script that can migrate the data from old format to new format.

**Comment by zaibon** [comment]
> Introduce an upgrade script that can migrate the data from old format to new format.

I like this
