### ISSUE TITLE
minio cannot restart if all the shards are not reachable

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#12]
I was testing the monitoring action of the minio template and I notice the process was not coming back as it should. After inspection turns out minio doesn't start if it can't reach all the shards specified in the configuration.
We'll have to decide how we handle this, cause I think that in production some shards would be down, but we still have enough available shards to fulfill the storage policy, so minio should still be able to start.

**Comment by muhamadazmy** [comment]
Fixed
Minio will log connection errors in a zos format so robot can take care of the failed zdb nodes.
