### ISSUE TITLE
Clicking the browser's back button in the minio web interface does not return to the previous level in the hierarchy

### ISSUE THREAD

**Issue by OldhamMade** [threefoldtech/minio#120]
## Steps to Reproduce (for bugs)
1. Create a nested storage hierarchy
2. Navigate to a leaf dir
3. Click the back button

## Expected Behavior
The view should change to the parent directory/folder

## Current Behavior
The browser loads the previous page in it's own history, which may not be the minio interface at all.

## Possible Solution
Use `history.pushState()` in JavaScript on each view change to ensure that there is a consistent history for the browser to use.

## Your Environment
* https://hub.grid.tf/tf-autobuilder/minio:v201028.83658.0-dev.flist
* Browser/OS info: https://www.whatsmybrowser.org/b/GTF94

**Comment by muhamadazmy** [comment]
the web UI for minio is part of minio core, we don't touch the UI in our fork, instead this bug should be moved to https://github.com/minio/minio instead..
