### ISSUE TITLE
rebase our fork to the latest version of minio

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#13]
This has been an awful amount of time since we bring change happening upstream into our fork.
We should make this happens, then define a process where we can rebase from upstream on regular basic to never get in the current situation anymore

**Comment by zaibon** [comment]
@muhamadazmy Can you start having a look how much work that would be. 
Our fork seems to be 6 month old so would be nice to be able to get back on track and put something in place where we rebase periodically.

**Comment by muhamadazmy** [comment]
Yes, sure. but shouldn't we try to reimplement in a way that it can be merged upstream so we don't have to rebase every few months ?

Anyway, I will rebase and see

**Comment by zaibon** [comment]
> shouldn't we try to reimplement in a way that it can be merged upstream so we don't have to rebase every few months ?

yes of course, that was the idea since day one: https://github.com/threefoldtech/minio/issues/23
But this issue doesn't seems to go anywhere so far.
Probably best thing do to is to contact the maintainer of minio and see what they would requires from us to accept a new gateway

**Comment by muhamadazmy** [comment]
I think if the code was clean enough and is generic enough to work against any key-value store (not only zdb) it should be acceptable. Other specific changes like tlog and such can still be maintained in our code. But i like the idea of contacting the maintainers of minio. Do u know what is the official way to do it ?

**Comment by zaibon** [comment]
>  key-value store (not only zdb) 
Why ? I don't think the problem. Also 0-stor has all the logic and it works on top of 0-db. I really don't see the issue there. But let's see what they will say.


Easiest way to contact them is to create an issue on their repo. explain how plan and let's ask them requirements.
