### ISSUE TITLE
bitrot protection

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#15]
I know 0-stor provide some health check and repair primitives but I've no idea if this has been integrated into our minio gateway code.

What we want to achieve is that periodically, we check the health of all the objects and repair them if necessary. 
This is also going to be used in cases we have dead data shards. Having dead shards will automatically mark the object as not healthy thought, so the normal periodic health check should detect them but in some cases, we know in advance that some shards are going to go down (disk replacement,...) So we would add a mechanism that manually trigger the healing processes.

**Comment by muhamadazmy** [comment]
We have 2 methods that I think we can used here:

- https://godoc.org/github.com/threefoldtech/0-stor/client#Client.Check
- https://godoc.org/github.com/threefoldtech/0-stor/client#Client.Repair

**Comment by zaibon** [comment]
> We have 2 methods that I think we can used here:

    https://godoc.org/github.com/threefoldtech/0-stor/client#Client.Check
    https://godoc.org/github.com/threefoldtech/0-stor/client#Client.Repair

That's the one indeed

**Comment by muhamadazmy** [comment]
I suggest that this be implemented as a stand alone tool that is packed in the minio flist. It can then be scheduled to run by either the robot or the zos built in `recurring_period` option. 

Then it can run every (say 30min) and traverse the entire metadata directory and check/repair all objects available at the time.

@zaibon what do u think ?

**Comment by zaibon** [comment]
@muhamadazmy idea sounds good. If you could formalize this idea a bit more so we can verify we ddon't forget any edge cases

**Comment by john-kheir** [comment]
issue: https://github.com/threefoldtech/minio/issues/35

**Comment by zaibon** [comment]
issue: #35 was not really a issue, so this one doesn' t have to be re-open
