### ISSUE TITLE
Create proper metadata stor

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/minio#24]
*Issue migrated from [https://api.github.com/repos/gigforks/minio/issues/34](), opened by @iwanbk*

We currently use simple file based metadata which is not:
- reliable
- work in distributed minio

one candidate is to use 0-metadata https://github.com/zero-os/0-metadata

It is blocked by #36

**Comment by rkhamis** [comment]
*commented by @iwanbk
Implemented at #50*

**Comment by rkhamis** [comment]
*commented by @iwanbk
> Implemented at #50

Not yet, was closing wrong issue*

**Comment by zaibon** [comment]
we have zerodb support for metadata since then. so we can close this one
