### ISSUE TITLE
Configurable backend for minio metadata

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/minio#3]
Have ZDB as a backend for minio's metadata

@muhamadazmy please add specs

**Comment by muhamadazmy** [comment]
After a meeting we Kristof we agreed to use zdb as metadata transaction logs. Basically all meta of a minio node will be maintained on disk, while a transaction log is kept in ZDB. This way metadata can be rolledback, synced to other nodes, and restored if needed.

I will rollback the changes I made so far and start over with the new approach

**Comment by muhamadazmy** [comment]
## Workflow of metadata transaction logs

### Single Instance Setup
- Each minio node, will always write metadata changes (transaction log) to a single zdb instance that is configured. ZDB are the source of truth, which means failure to write the change to zdb is an error, and the operation only succeed if the transaction log was created successfully.
- After the tlog record is created, the meta is commited to the local hard-disk, this meta directory is used by minio to serve the files (and directory structures)
- On start, minio must make sure the local meta is synchronised with it's tlog zdb. Playing missing changes until the local changes matches the last record in tlog. This can happen if minio crashed or failed, after committing one or more records to zdb. This means that minio must keep track of the position of a the last tlog key.

### Master/Slave Setup
- In a master/slave setup, the master (active) node will have a setup similar to Single instance setup. It should not be aware of Slave instances
- A slave will follow the master zdb and consume all updates.
- The updates will be committed to 2 locations, the slave zdb tlog server, and filesystem for fast recovery.
- A salve should be aware that it's a passive node, which means it should not accept changes to meta via it's interface (u can't create, or delete bucket, nor upload or delete files).
Once a slave is promoted to master (config rewritten, then signaled or restarted) the node will run in Master mode.

![Sequence Diagram](http://www.plantuml.com/plantuml/png/POwzJkj048NxUOgZD3IG1qY14cuQYaXNG4KtU2V9YFsnTiQHoDEpZeKLoSqMvvlpdTsQS_KXHPBiwZzO7TXSAWwQjQp0XfGeiFCNcynqh_OzmR24d_kNYLrdwNlaYzmvxSuvmRbbrmMQromGvUA2ggUpenn7qSTP3IMtSCW6pR1RAPKWZr17A6BvmOcxJdh7qCV2GVC9HutIcXL1gtIExipvr18lIE9C5-NMD-p-lvBaW76PKiBJCz9rWrtVjtHgpNdOu5z9INsqXFPlelLwJR6K7bu78RJkU6bfWpVX08xnRvdGuXjSw6Uo76XNj6tFaE8l)
