### ISSUE TITLE
Inconsistent bucket delete operation

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/minio#30]
Deleting a bucket containing objects then creating a new bucket with same name is not working as expected!

## Expected Behavior
Newly created one must be empty

## Current Behavior
I get back old objects in the deleted bucket in my newly created bucket

## Possible Solution
Actually deleting files, or mark them as deleted so they can be hidden
or may be when creating a bucket, it should have unique ID associated with it, we use that ID as prefix for objects internally. and we also may have a table containing these mappings to do resolution
then when deleting a bucket, and creating a new one it gets a new ID which is different than the old one
so old objects are no more associated to newly created bucket

## Steps to Reproduce (for bugs)

1. Create bucket (buck1)
2. Upload some objects
3. Delete `buck1`
4. Create new bucket `buck1`

## Your Environment

* Version used (`minio version`): Minio with zerostor gateway `zerostor` branch

* Operating System and version (`uname -a`): `Linux hamdy 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* Link to your project: https://github.com/threefoldtech/minio

**Comment by despiegk** [comment]
can we reproduce this

**Comment by muhamadazmy** [comment]
fixed here 

https://github.com/threefoldtech/minio/commit/53239f6520f4b34d427d919ea30d0dc444036cda
