### ISSUE TITLE
Sometimes files downloaded are empty and restart needed

### ISSUE THREAD

**Issue by Hamdy** [threefoldtech/minio#32]
Retrieving files working, but files downloaded are 0-byte size

## Expected Behavior
Downloaded files should be correct everytime
## Current Behavior
Sometimes I download files but I see they having 0-bytes size. after restarting 0-db and minio things work
## Possible Solution
!!

## Steps to Reproduce (for bugs)

It's occasional

## Context

Just while playing and adding/deleting files for long time
## Your Environment

* Version used (`minio version`): Minio with zerostor gateway `zerostor` branch

* Operating System and version (`uname -a`): `Linux hamdy 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

* Link to your project: https://github.com/threefoldtech/minio

**Comment by zaibon** [comment]
@Hamdy please try to get a small program that reproduce this everytime

**Comment by zaibon** [comment]
close for inactivity
