### ISSUE TITLE
Data is not corrected using bitrot

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/minio#35]
## Scenario
1- Create s3 service 
2- Corrupt some data in any of the namespaces of the minio of that s3 service
3- Get the minio container and execute this command to trigger repair.
```
res = self.s3.minio_container.client.system('minio gateway zerostor-repair --config-dir /bin').get(300)

ipdb> res
STATE: 0 SUCCESS
STDOUT:

STDERR:
time="2018-10-25T12:37:39Z" level=info msg=config config="{{5mofubstqgu8jky70kgk30mr38fvg3gs 0ce9c99b {[10.102.64.213:1038 10.102.178.130:1046 10.102.234.243:1044 10.102.147.99:1046 10.102.234.229:1054 10.102.117.236:1049 10.102.71.171:1048 10.102.114.69:1047] {1048576 {blake2b_256 } {default snappy} { aes} {4 2}} {false    }}} {{ { }} { { }} 0xc4202ab650 <nil>}}"

DATA:


```

## Actual Result:
4- Subscribe to the job of the  minio and stream the output
```ipdb> sub = self.s3.minio_container.client.subscribe('minio.0775de8b-3049-4f4f-af67-626a48e9f4a5')
ipdb> sub.stream()
AccessKey: admin 
SecretKey: adminadmin 

Browser Access:
   http://0.0.0.0:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myzerostor http://0.0.0.0:9000 admin adminadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
time="2018-10-25T10:14:42Z" level=info msg="MakeBucketWithLocation bucket=n2y4vevsdtik3g5u, location=\n"
{"error":"Namespace not found","level":"error","msg":"failed to write data to random shard","shard":"10.102.114.69:1047","time":"2018-10-25T10:14:43Z"}
time="2018-10-25T10:17:28Z" level=info msg="MakeBucketWithLocation bucket=e4x76phdlevoikv1, location=\n"
{"error":"Namespace not found","level":"error","msg":"failed to write data to random shard","shard":"10.102.114.69:1047","time":"2018-10-25T10:17:29Z"}
time="2018-10-25T12:33:03Z" level=info msg="MakeBucketWithLocation bucket=rkg8ho2sf9giamjy, location=\n"
{"error":"Namespace not found","level":"error","msg":"failed to write data to random shard","shard":"10.102.114.69:1047","time":"2018-10-25T12:33:04Z"}
time="2018-10-25T12:36:25Z" level=info msg="MakeBucketWithLocation bucket=8wamkwgqn6kp67bs, location=\n"
^CKeyboardInterrupt
2018-10-25T12:46:30Z
*** KeyboardInterrupt
```

2- After a while the data hasn't been corrected and all the logs i got is as stated above.

**Comment by zaibon** [comment]
@john-kheir can you explain how exactly did you "corrupted" the data. Cause here the error seems to be the namespace doesn't exist at all, which is different from having actual data corrupted.

**Comment by john-kheir** [comment]
@zaibon simply i go to the namespace itself inside zos node and find any shard and corrupt it .. but i was talking to @muhamadazmy and he told me even if you did that, the bitrot scans keys of a valid file for instance  and when it finds corrupted data of  certain keys it, recalculate the data and write it in a different key which is in a different location in the shards.. so the shard i corrupted won't be corrected again however the data is already corrected in another place .. so simply this ticket is invalid since my check is wrong .. in btw i don't know for now how to check if the bitrot worked .. but i'm trying to find a way

**Comment by john-kheir** [comment]
And concerning the namespace don't exist .. this error is related to s3 service .. but irrelevant in this ticket .. i will close the ticket but @zaibon feel free to add any comments.

**Comment by zaibon** [comment]
@john-kheir 
> in btw i don't know for now how to check if the bitrot worked

What you can do is, corrupt the data, health it, then turn of some shards so you only have the minimum viable and check if you can download the files properly. This would ensure that the data is healthy again on all shards
