### ISSUE TITLE
Vdisk SSD failure for  minio  trigger self healing in a weird way

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/minio#53]
Findings After disabling ssd using command line:
-------------------------------------------------
cmd: ```echo 1 > /sys/block/{}/device/delete```

- I can't reach the old active vm after a while 
- Another vm has been created.
- The new vm was working in slave mode in the begging when i tried to upload a file 
  then it moved to active mode and i was able to upload a file and i also can see that 
  the active instance took the ip of the new vm created.
- The passive instance still using old passive vm ip and it gave an internal error in the begining 
  when i tried to upload a file but eventually it  acted as passive vm.
- After reaching steady state .. new vm acted as active and old passive vm is acting as passive 
 and i uploaded file to active vm and it has been reflected to passive vm

 bugs:
------
- New vm didn't act as passive but it acted as active
- Old passive vm didn't switch to act as active. (At one time it came back and in another trial it didn't)

Note:
-----
the logs from the old active minio container was as follows
```
{"error":"Internal Error (data)","level":"error","master":false,"msg":"failed to write transaction log","namespace":"62db1987-bebb-4308-b4d9-7b3453935d34_tlog","subsystem":"tlog","time":"2018-11-27T07:26:21Z","tlog":"10.102.133.88:1024"}
```
For this case tlog and vdisk were using same ssd

Question:
---------
Also we shouldn't wait for someone to upload to minio to find out that there is ssd failure .. Can zerodb service write into ssd mounting point ?

**Comment by john-kheir** [comment]
@muhamadazmy comment:
We have a self healing path where passive will not be promoted is when both active and passive fails:

- If both active vm, and passive vm are detected as down for any reason

    1- active vm is redeployed (as active) but persist the tlog
    2- passive vm is redeployed (as passive) with new tlog
Once both are up, minio will take care synching master tlog (tlog of active) to passive
(longer down time)
- If only active is down

  1- promote passive (goes much faster)
  2- redeploy a new passive machine (usually active re purposed)
(much shorter down time)
- if only passive is down

   redeploy
   (no down time)

**Comment by john-kheir** [comment]
@serboctor comment:
```I'm not sure if the vdisk and tlog were using the same ssd but I'm assuming they are```
why are you assuming they are? They might not even be on the same node. And you can easily find that out. the dm_vm service has the node id in its data, this tells you which node the vdisk and vm will be created on, and you can investigate the node further. And also from the s3 data, you can find out on the robot address and node is of the tlog namespace and investigate from there.

**Comment by zaibon** [comment]
I'll try to refactor things to allow us to try to avoid having this situation where tlog and vdisk are on the same zdb.

**Comment by rkhamis** [comment]
@zaibon let's keep this ticket open so we can fix for tfgrid that they can be deployed on fewer resources.
We'll then move to 9.6.0 when we're ready

**Comment by zaibon** [comment]
Started working on modifying the s3 template to avoid this situation: https://github.com/threefoldtech/0-templates/pull/252/files

**Comment by zaibon** [comment]
Code has been update to ensure we have a proper spearing of all VMs and tlog namespaces.

**Comment by Pishoy** [comment]
I test vdisk failure of passive minio  and i works but i need to understand some points 
1 -after i fail the passive vdisk by echo 1 .. ,when i upload files to active, the files replicated between passive and active quickly while i dropped the passive vdisk !
1- i see from logs, there is a new vm created after failure but when i check the configuration of passive minio , they vdisk still pointing to old storage pool mount point which does not exist anymore, may the new configuration does not updated on minio configuration yaml 
2 - replication working properly after failure 
3 - below some steps i catch to be reviewed on verification steps  
https://gist.github.com/Pishoy/4ba4d7bc1426cfdebd052dbad01bae0f

**Comment by john-kheir** [comment]
### Failure for active minio vm vdisk:

After Causing a failure (using echo command) and trying to upload to the minio and writing to the disk physically .. nothing was triggered .. All active and pssive s3 logs are fine.. and i still can upload to active minio and it is getting replicated to passive minio.

##### there were some failure in the passive minio but not sure why:
```
John Kheir, [02.12.18 08:45]
In [15]: job_p.stream()
time="2018-12-02T06:23:25Z" level=info msg="Got SIGHUP:reload the config"
time="2018-12-02T06:23:25Z" level=info msg="closing zerostor"
time="2018-12-02T06:23:25Z" level=info msg="calling cancel function"
time="2018-12-02T06:23:25Z" level=info msg="terminate synchronization due to cancel"
time="2018-12-02T06:23:25Z" level=info msg="initializing tlog zdb"

Trace: 1: cmd/web-handlers.go:1098:cmd.toWebAPIError()
       2: cmd/web-handlers.go:967:cmd.toJSONError()
       3: cmd/web-handlers.go:136:cmd.(*webAPIHandlers).MakeBucket()
       4: reflect/value.go:447:reflect.Value.call()
       5: reflect/value.go:308:reflect.Value.Call()
       6: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
       7: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       8: cmd/generic-handlers.go:584:cmd.pathValidityHandler.ServeHTTP()
       9: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      10: :0:()
      11: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      12: :0:()
      13: cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
      14: :0:()
      15: cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
      16: :0:()
      17: cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
      18: :0:()
      19: cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
      20: :0:()
      21: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      22: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      23: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      24: cmd/generic-handlers.go:474:cmd.resourceHandler.ServeHTTP()
      25: cmd/auth-handler.go:265:cmd.authHandler.ServeHTTP()
      26: :0:()
      27: pkg/http/server.go:111:http.(*Server).Start.func1()
      28: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      29: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      30: net/http/server.go:2694:http.serverHandler.ServeHTTP()
      31: net/http/server.go:1830:http.(*conn).serve()
[2018-12-02T06:28:06.715023415Z] [ERROR] Unexpected error, please report this issue at https://github.com/minio/minio/issues (minio running in slave mode)
time="2018-12-02T06:28:23Z" level=info msg="Got SIGHUP:reload the config"
time="2018-12-02T06:28:23Z" level=info msg="closing zerostor"
time="2018-12-02T06:28:23Z" level=info msg="calling cancel function"
time="2018-12-02T06:28:23Z" level=info msg="terminate synchronization due to cancel"
time="2018-12-02T06:28:23Z" level=info msg="initializing tlog zdb"
time="2018-12-02T06:28:23Z" level=info msg=StorageInfo

John Kheir, [02.12.18 08:45]


Trace: 1: cmd/web-handlers.go:1098:cmd.toWebAPIError()
       2: cmd/web-handlers.go:967:cmd.toJSONError()
       3: cmd/web-handlers.go:136:cmd.(*webAPIHandlers).MakeBucket()
       4: reflect/value.go:447:reflect.Value.call()
       5: reflect/value.go:308:reflect.Value.Call()
       6: vendor/github.com/gorilla/rpc/v2/server.go:137:v2.(*Server).ServeHTTP()
       7: vendor/github.com/gorilla/mux/mux.go:107:mux.(*Router).ServeHTTP()
       8: cmd/generic-handlers.go:584:cmd.pathValidityHandler.ServeHTTP()
       9: cmd/generic-handlers.go:65:cmd.requestSizeLimitHandler.ServeHTTP()
      10: :0:()
      11: cmd/crossdomain-xml-handler.go:51:cmd.crossDomainPolicy.ServeHTTP()
      12: :0:()
      13: cmd/generic-handlers.go:231:cmd.redirectHandler.ServeHTTP()
      14: :0:()
      15: cmd/generic-handlers.go:289:cmd.minioReservedBucketHandler.ServeHTTP()
      16: :0:()
      17: cmd/generic-handlers.go:258:cmd.cacheControlHandler.ServeHTTP()
      18: :0:()
      19: cmd/generic-handlers.go:359:cmd.timeValidityHandler.ServeHTTP()
      20: :0:()
      21: vendor/github.com/rs/cors/cors.go:190:cors.(*Cors).Handler.func1()
      22: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      23: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      24: cmd/generic-handlers.go:474:cmd.resourceHandler.ServeHTTP()
      25: cmd/auth-handler.go:265:cmd.authHandler.ServeHTTP()
      26: :0:()
      27: pkg/http/server.go:111:http.(*Server).Start.func1()
      28: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      29: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
      30: net/http/server.go:2694:http.serverHandler.ServeHTTP()
      31: net/http/server.go:1830:http.(*conn).serve()
[2018-12-02T06:42:01.986944396Z] [ERROR] Unexpected error, please report this issue at https://github.com/minio/minio/issues (minio running in slave mode)
^CKeyboardInterrupt
2018-12-02T06:42:14Z
```

**Comment by muhamadazmy** [comment]
We did a deep dive of this issue and found the following:
# Scenario
- Install an s3 redundant instance
- Validate installation (active passive setup with working synchronisation) 
- Find and fail the zdb instance that hosts the active machine vdisk following the path (DmVm - > Node -> Vm -> VDisk -> Zdb)
- Disable the disk of the zdb instance

# Test
- When uploading new files, the upload continue to work.

# Tracing the issue
- Test write inside zdb container, return an error as expected since the physical disk no longer exists.
- Writing a file on the vdisk (from the minio vm) works normally.
- Checking direct write to zdb works (?) this is an error since zdb can't actual commit the data to disk
- Checking zdb errors shows on going error messages (IO Errors)

# Conclusion
To minio (and the vm) writing to disk works, because zdb never returned an error on writing. Hence no self healing kicked in. 

> We are not sure how much data zdb can keep in memory before crashing because we tried to write 1G file to the vdisk and was still successfully. ZDB error logs still going

![image](https://user-images.githubusercontent.com/10920323/49341260-85a98d00-f653-11e8-841e-6f07b517e8aa.png)

> NOTE:
Tlog failure is detected almost immediately (error returned to minio) but I think this is due to tlog zdb runs in seq mode, while vdisk zdb runs in user mode.

**Comment by muhamadazmy** [comment]
@maxux we need a fix for zdb to return an error when zdb can't write data to disk. We need this as soon as possible, it's blocking us from releasing.

**Comment by maxux** [comment]
Should be fixed by https://github.com/threefoldtech/0-db/commit/14cc559cc2af52b3fa331a92616cd72b363d303b

**Comment by Pishoy** [comment]
close it as it tested and vdisk failure trigger the self healing on both passive and active
