### ISSUE TITLE
Refactor integration code with 0-stor

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/minio#72]
Currently the code is so messy and not generic enough, and really hard to maintain. Lots of code parts are done in multiple places.

We need to use the current experience we have atm to re implement the integration cleanly.
https://docs.google.com/document/d/1WAs1MOlaZ8Ed32FrtQZ_ViEsps9V8RnIGqzFADSxFAw/

**Comment by serboctor** [comment]
Progress tracker for Object Layer:

- [x] GetBucketInfo
- [x] DeleteBucket
- [x] ListBuckets
- [x] MakeBucketWithLocation
- [x] GetBucketPolicy 
- [x] SetBucketPolicy
- [x] DeleteBucketPolicy
- [x] DeleteObject
- [x] CopyObject
- [x] GetObject
- [x] ListObjects
- [x] ListObjectsV2
- [x] PutObject
- [x] NewMultipartUpload
- [x] PutObjectPart
- [x] CopyObjectPart
- [x] CompleteMultipartUpload
- [x] AbortMultipartUpload
- [x] ListMultipartUploads
- [x] ListObjectParts
- [x] Shutdown
- [x] StorageInfo

- [x] tlog layer
- [x] check and repair layer

**Comment by zaibon** [comment]
@muhamadazmy @serboctor I just read the document regarding this refactor work. Looks good, but I have one question regarding migration to this new implementation. Cause it seems the metadata organization is not going to be compatible with the current one.
Can we make sure to open an issue about migration tool that will need to be created in order to be able to update existing archive to this new version?

**Comment by serboctor** [comment]
Currently working on the PR comments.
I will resume writing tests afterwards.

**Comment by serboctor** [comment]
I am still verifying minio mint tests against my branch and fixing Azmy's newly communicated PR comments.

**Comment by serboctor** [comment]
Mint tests all pass now and all PR comments are done. I resumed writing tests.

**Comment by serboctor** [comment]
Finished object gateway tests and zerostor client tests.

**Comment by serboctor** [comment]
Rebased the master from minio's master and rebased my branch from master. They removed vendoring and all the dependencies are messed up. I fixed most things and I am trying to reach a green build again.

**Comment by serboctor** [comment]
I fixed some tests which had race conditions. The build is still not green because of coverage

**Comment by serboctor** [comment]
I fixed the `make coverage` and now the build is green. I still need to write more tests but I'll pause that for now until I am done with more critical tasks.
