### ISSUE TITLE
re-branding system

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/minio#8]
In order for some of our user to have a more personalize minio web portal we want to be able to re-brand it with their logo.

Since minio is distributed as a single binary it could be we'll have to hack a bit to have the possibility to load an image at startup or something

**Comment by rkhamis** [comment]
https://github.com/threefoldtech/minio/pull/11

**Comment by zaibon** [comment]
hard coded branding has been done. I'll move this issue back to backlog so we can work on it to have a configurable re-branding system

**Comment by muhamadazmy** [comment]
@zaibon this issue is about the logo, right? i think we should close it now, right ?

**Comment by zaibon** [comment]
Indeed
